"""wiki_init.py — Bootstrap a new LLM Wiki space inside the configured vault.

Creates ``<vault>/<wiki_folder>/<slug>/`` with the canonical layout:

    <slug>/
    ├── SCHEMA.md          (frozen contract, populated from template)
    ├── index.md           (auto-regenerated by compile)
    ├── log.md             (append-only journal, seeded with init row)
    ├── raw/
    │   ├── _README.md
    │   ├── articles/  docs/  transcripts/  assets/   (empty dirs with .gitkeep)
    ├── pages/             (populated only in project mode)
    ├── entities/  concepts/  comparisons/  queries/  (empty dirs with .gitkeep)

No LLM is involved. No vault writes happen outside the new wiki-space.

Usage:
    python3 scripts/wiki_init.py <slug> --mode project --title "Demo Project"
    python3 scripts/wiki_init.py <slug> --mode corpus --title "Reading List"

Exit codes:
    0 — wiki-space created
    1 — bad arguments / config
    2 — wiki-space already exists (use --force to overwrite)
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

try:
    from scripts.config import PROJECT_ROOT, load_config as _load_config
    from scripts.wiki_models import (
        CORE_PAGES,
        WIKI_MODES,
        WIKI_RAW_KINDS,
        is_valid_slug,
    )
except ModuleNotFoundError:
    from config import PROJECT_ROOT, load_config as _load_config
    from wiki_models import (
        CORE_PAGES,
        WIKI_MODES,
        WIKI_RAW_KINDS,
        is_valid_slug,
    )


TEMPLATE_ROOT = PROJECT_ROOT / "templates" / "wiki"
SUPPORTED_LANGS = ("en", "ru")
DEFAULT_LANG = "en"

# Sub-directories that exist in every wiki-space, regardless of mode.
ALWAYS_DIRS = ("entities", "concepts", "comparisons", "queries", "readouts")


def render_template(rel: str, ctx: dict, lang: str = DEFAULT_LANG) -> str:
    """Read templates/wiki/<lang>/<rel> and substitute {{placeholders}} from ctx."""
    if lang not in SUPPORTED_LANGS:
        raise ValueError(f"unsupported lang '{lang}', expected one of {SUPPORTED_LANGS}")
    src = TEMPLATE_ROOT / lang / rel
    text = src.read_text(encoding="utf-8")
    for key, value in ctx.items():
        text = text.replace("{{" + key + "}}", str(value))
    return text


def _create_dir_with_keep(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    keep = path / ".gitkeep"
    if not keep.exists():
        keep.write_text("", encoding="utf-8")


def init_wiki_space(
    root: Path,
    slug: str,
    mode: str,
    title: str,
    description: str,
    force: bool,
    lang: str = DEFAULT_LANG,
) -> None:
    """Materialize the wiki-space layout under root."""
    if root.exists() and not force:
        raise FileExistsError(f"wiki-space already exists at {root}")
    if root.exists() and force:
        # Don't recursively delete — just overwrite the templates we own.
        # Existing pages outside the template set are preserved.
        pass

    today = date.today().isoformat()
    ctx = {
        "slug": slug,
        "title": title or slug,
        "mode": mode,
        "description": description or _no_description_placeholder(lang),
        "date": today,
    }

    root.mkdir(parents=True, exist_ok=True)

    # Meta files at root
    (root / "SCHEMA.md").write_text(
        render_template("SCHEMA.template.md", ctx, lang=lang), encoding="utf-8"
    )
    (root / "log.md").write_text(
        render_template("log.template.md", ctx, lang=lang), encoding="utf-8"
    )

    # raw/ with kind subfolders + README
    raw_root = root / "raw"
    raw_root.mkdir(exist_ok=True)
    (raw_root / "_README.md").write_text(
        render_template("raw/_README.template.md", ctx, lang=lang), encoding="utf-8"
    )
    for kind in WIKI_RAW_KINDS:
        _create_dir_with_keep(raw_root / kind)

    # Always-on bucket dirs
    for d in ALWAYS_DIRS:
        _create_dir_with_keep(root / d)

    # Core pages (project mode only)
    if mode == "project":
        pages_dir = root / "pages"
        pages_dir.mkdir(exist_ok=True)
        for core in CORE_PAGES:
            (pages_dir / f"{core}.md").write_text(
                render_template(f"pages/{core}.template.md", ctx, lang=lang), encoding="utf-8"
            )

    # index.md is rendered last so the "Core pages" section can list the
    # pages we just materialized — keeps the freshly-init'd space lint-clean.
    if mode == "project":
        core_lines = "\n".join(f"- [[{core}]]" for core in CORE_PAGES)
    else:
        core_lines = _no_core_pages_placeholder(lang)
    index_ctx = {**ctx, "core_pages_list": core_lines}
    (root / "index.md").write_text(
        render_template("index.template.md", index_ctx, lang=lang), encoding="utf-8"
    )


def _no_description_placeholder(lang: str) -> str:
    return {
        "ru": "_(описание не указано при инициализации)_",
        "en": "_(no description provided at init time)_",
    }.get(lang, "_(no description provided at init time)_")


def _no_core_pages_placeholder(lang: str) -> str:
    return {
        "ru": "_(режим corpus — фиксированных core-страниц нет)_",
        "en": "_(corpus mode — no fixed core pages)_",
    }.get(lang, "_(corpus mode — no fixed core pages)_")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Initialize a new LLM Wiki space inside the configured vault."
    )
    parser.add_argument("slug", help="kebab-case slug for the new wiki-space")
    parser.add_argument(
        "--mode",
        choices=list(WIKI_MODES),
        default=None,
        help="project (fixed core pages) or corpus (entities-only)",
    )
    parser.add_argument("--title", default=None, help="human-readable title")
    parser.add_argument(
        "--description", default=None, help="one-paragraph description for SCHEMA.md / overview"
    )
    parser.add_argument(
        "--force", action="store_true", help="overwrite meta + core templates if space exists"
    )
    parser.add_argument(
        "--lang",
        choices=list(SUPPORTED_LANGS),
        default=None,
        help="template language (defaults to [wiki].default_lang in config, or 'en')",
    )
    parser.add_argument(
        "--non-interactive", action="store_true", help="never prompt; reserved for parity"
    )
    args = parser.parse_args()

    if not is_valid_slug(args.slug):
        print(f"ERROR: slug '{args.slug}' is not valid kebab-case ASCII", file=sys.stderr)
        return 1

    config = _load_config(strict=True)
    vault_path = Path(config["vault"]["vault_path"]).expanduser()
    wiki_cfg = config.get("wiki", {})
    wiki_folder = wiki_cfg.get("wiki_folder", "LLM Wiki")
    mode = args.mode or wiki_cfg.get("default_mode", "project")
    if mode not in WIKI_MODES:
        print(f"ERROR: mode '{mode}' not in {list(WIKI_MODES)}", file=sys.stderr)
        return 1
    lang = args.lang or wiki_cfg.get("default_lang", DEFAULT_LANG)
    if lang not in SUPPORTED_LANGS:
        print(f"ERROR: lang '{lang}' not in {list(SUPPORTED_LANGS)}", file=sys.stderr)
        return 1

    root = vault_path / wiki_folder / args.slug

    try:
        init_wiki_space(
            root=root,
            slug=args.slug,
            mode=mode,
            title=args.title or args.slug,
            description=args.description or "",
            force=args.force,
            lang=lang,
        )
    except FileExistsError as exc:
        print(f"WIKI_ALREADY_EXISTS: {exc}", file=sys.stderr)
        return 2
    except OSError as exc:
        print(f"ERROR: failed to create wiki-space: {exc}", file=sys.stderr)
        return 1

    print(f"OK: created wiki-space at {root} (mode={mode}, lang={lang})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
